version: "3"

services:
    app:
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        volumes: 
            - .:/app/
        ports:
            - 3000:3000
            - 9229:9229

volumes:
    mongodb-data: